### PR TITLE
Fix impound

### PR DESCRIPTION
**Pull request by TonybynMp4**
should remove the vehicle the police impounded from the regular impound and fix the /depot bypassing the configured depotprice
didn't seem to break anything when i tested it so it should be all good :p

### CODE REVIEW

**Comment by JonasDev99** [comment]
And how will players be able to get their cars back if the police have impounded them?

**Comment by TonybynMp4** [comment]
> And how will players be able to get their cars back if the police have impounded them?

ask a police officer to get it out, no point of the police impound if they can just get it at the normal impound :p
the /depot 0 works if the cop just want to put the vehicle to the regular impound

**Comment by JonasDev99** [comment]
Btw the changes I made fixed the issue with the depot price, so this 
image
is no longer required.

**Comment by TonybynMp4** [comment]
using the impound of qb-policejob

**Pull request merged**
