### PR TITLE
Updated server side to check for keys and house ownership

### PR DESCRIPTION
**Pull request by SlimChances**

### CODE REVIEW

**Comment by OfficialRDB** [comment]
I'm still able tp pull people their cars out of their garage

**Comment by flash061** [comment]
Yeah that didn't fix it, I can still take other peoples cars out of their home garages

**Comment by SlimChances** [comment]
dang well im trying lol

**Comment by OfficialRDB** [comment]
> dang well im trying lol

I know you are. Thank you for that.

**Comment by SlimChances** [comment]
Okay so i updated my version and some stuff there and tested and it is working now.

**Comment by JonasDev99** [comment]
This should no longer be needed. The zone is only created if a player has a key to the house therfor a key check should not be necessary.

**Pull request closed without merging**
